name: churn-imbalanced-dvc-pipeline
on: [push]
permissions: write-all # Required for posting comments and reports

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Changed to a specific version for better compatibility

      - name: Install CML
        uses: iterative/setup-cml@v1

      - name: Install Dependencies
        run: |
          # Upgrade pip
          python -m pip install --upgrade pip
          # Install numpy first to ensure compatibility with scikit-learn
          pip install "numpy>=1.17.3,<1.24.0"
          # Install other dependencies
          pip install -r requirements.txt
        env:
          CXX: g++ # Ensures correct C++ compiler is used for sklearn and Cython compilation issues

      - name: Verify Installed Packages
        run: |
          # Print installed packages for debugging
          pip list

      - name: Remove File from Git Tracking
        if: "runner.os == 'Linux' && (hashFiles('outs_data/prepared_data.csv') != '')"
        run: |
          # Configure Git identity
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          # Stop Git from tracking the file that DVC needs to manage
          git rm -r --cached 'outs_data/prepared_data.csv'
          git commit -m "Stop tracking outs_data/prepared_data.csv"

      - name: Generate and Post Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run DVC pipeline
          dvc repro
          git fetch --prune

          # Generate the report
          echo "## Metrics" > report.md
          dvc metrics diff --md main >> report.md

          # Append confusion matrix to the report
          echo "## Confusion Matrix" >> report.md
          echo "![](./conf_matrix.png)" >> report.md

          # Post the report as a comment
          cml comment create --token ${{ secrets.GITHUB_TOKEN }} report.md